// Global State Management
let currentTopic = '';
let currentLevel = '';
let flowchartData = null;
let currentStepIndex = 0;
let currentSubStepIndex = 0;
let isPlaying = false;
let tourTimeout = null;
let allNodes = [];